modules/admin/controllers/DatabaseCategoryController.php
<?php

namespace app\modules\admin\controllers;

use richardfan\sortable\SortableAction;
use Yii;
use app\models\DatabaseCategory;
use app\models\search\DatabaseCategorySearch;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * DatabaseCategoryController implements the CRUD actions for DatabaseCategory model.
 */
class DatabaseCategoryController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function actions(){
        return [
            'sortItem' => [
                'class' => SortableAction::class,
                'activeRecordClassName' => DatabaseCategory::class,
                'orderColumn' => 'priority',
            ]
        ];
    }

    /**
     * Lists all DatabaseCategory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DatabaseCategorySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DatabaseCategory model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DatabaseCategory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DatabaseCategory();

        if ($model->load(Yii::$app->request->post())) {
            $model->priority = $this->getNumberLastRecord();
            $model->save();
            $image = UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->link = $this->saveImage($model, $image, 'category');
            }

            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing DatabaseCategory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            $image =  UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->link = $this->saveImage($model, $image, 'category');
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing DatabaseCategory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        /** @var DatabaseCategory $model */
        $model = $this->findModel($id);
        if(is_file(Yii::getAlias('@webroot').$model->link)) {
            unlink(Yii::getAlias('@webroot').$model->link);
        }

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DatabaseCategory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DatabaseCategory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DatabaseCategory::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Сохранение изображения
     * @param $model DatabaseCategory
     * @param $image UploadedFile
     * @param $type string
     * @return string
     */
    private function saveImage($model, $image, $type)
    {
        $path = '/images/category/'.$model->id.'_'.$type.'.'.$image->extension;

        if(!is_dir(\Yii::getAlias('@webroot').'/images/category')) {
            mkdir(\Yii::getAlias('@webroot').'/images/category');
        }
        $image->saveAs(\Yii::getAlias('@webroot').$path);
        return $path;
    }

    /**
     * Получение номера приоритетности для новой записи
     * @return int|string
     */
    private function getNumberLastRecord()
    {
        return DatabaseCategory::find()->count() + 1;
    }
}

modules/admin/controllers/ProductCardController.php
<?php

namespace app\modules\admin\controllers;

use richardfan\sortable\SortableAction;
use Yii;
use app\models\ProductCard;
use app\models\search\ProductCardSearch;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * ProductCardController implements the CRUD actions for ProductCard model.
 */
class ProductCardController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function actions(){
        return [
            'sortItem' => [
                'class' => SortableAction::class,
                'activeRecordClassName' => ProductCard::class,
                'orderColumn' => 'priority',
            ]
        ];
    }

    /**
     * Lists all ProductCard models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductCardSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ProductCard model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProductCard model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductCard();

        if ($model->load(Yii::$app->request->post())) {
            if($model->info != '') {
                $model->info = json_encode($model->info, JSON_UNESCAPED_UNICODE);
            } else {
                $model->info = null;
            }
            $model->priority = $this->getNumberLastRecord();
            if($model->database_category_id == 0) {
                $model->database_category_id = null;
            }
            $model->save();
            $image = UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->link = $this->saveImage($model, $image, 'product');
            }

            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ProductCard model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            if($model->info != '') {
                $model->info = json_encode($model->info, JSON_UNESCAPED_UNICODE);
            } else {
                $model->info = null;
            }
            if($model->database_category_id == 0) {
                $model->database_category_id = null;
            }

            $image =  UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->link = $this->saveImage($model, $image, 'product');
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $model->info = json_decode($model->info);

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ProductCard model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        /** @var ProductCard $model */
        $model = $this->findModel($id);
        if(is_file(Yii::getAlias('@webroot').$model->link)) {
            unlink(Yii::getAlias('@webroot').$model->link);
        }

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ProductCard model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ProductCard the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProductCard::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Сохранение изображения
     * @param $model ProductCard
     * @param $image UploadedFile
     * @param $type string
     * @return string
     */
    private function saveImage($model, $image, $type)
    {
        $path = '/images/product/'.$model->id.'_'.$type.'.'.$image->extension;

        if(!is_dir(\Yii::getAlias('@webroot').'/images/product')) {
            mkdir(\Yii::getAlias('@webroot').'/images/product');
        }
        $image->saveAs(\Yii::getAlias('@webroot').$path);
        return $path;
    }

    /**
     * Получение номера приоритетности для новой записи
     * @return int|string
     */
    private function getNumberLastRecord()
    {
        return ProductCard::find()->count() + 1;
    }
}

modules/admin/views/product-card/_form.php
<?php

use app\models\DatabaseCategory;
use app\models\ProductCard;
use kartik\file\FileInput;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use unclead\multipleinput\MultipleInput;
use vova07\imperavi\Widget;

/* @var $this yii\web\View */
/* @var $model app\models\ProductCard */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="product-card-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'short_description')->widget(Widget::class, [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'plugins' => [
                'fullscreen',
                'table',
                'fontcolor',
                'fontfamily',
                'fontsize',
            ],
        ],
    ]); ?>

    <?= $form->field($model, 'full_description')->widget(Widget::class, [
        'settings' => [
            'lang' => 'ru',
            'minHeight' => 200,
            'plugins' => [
                'fullscreen',
                'table',
                'fontcolor',
                'fontfamily',
                'fontsize',
            ],
        ],
    ]); ?>

    <?= $form->field($model, 'info')->widget(MultipleInput::class, [
        'min' => 0,
        'max' => 15,
        'columns' => [
            [
                'name'  => 'key',
                'type'  => 'textInput',
                'title' => 'Описание',
                'value' => function($data) {
                    return $data->key;
                }
            ],
            [
                'name'  => 'value',
                'type'  => 'textInput',
                'title' => 'Значение',
                'value' => function($data) {
                    return $data->value;
                }
            ]
        ]
    ]) ?>

    <?= $form->field($model, 'is_visible')->checkbox() ?>

    <?= $form->field($model, 'is_available')->checkbox() ?>

    <?= $form->field($model, 'is_pre_order')->checkbox() ?>

    <?= $form->field($model, 'date_available')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date_pre_order')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'image')->widget(FileInput::class, [
        'options'       => ['accept' => 'image/*'],
        'pluginOptions' => [
            'initialPreview'=>[
                $model->link
            ],
            'allowedFileExtensions' => ['jpg','gif','png'],
            'previewFileType'       => 'image',
            'initialPreviewAsData'  => true,
            'fileActionSettings'    => [
                'showUpload' => false,
                'showDrag'   => false,
            ],
            'initialPreviewConfig' =>  [
                [
                    'caption' => $model->link,
                    'url'     => Url::toRoute(['project/delete-image']),
                    'key'     => $model->id,

                ]
            ],
        ],
    ]) ?>

    <?= $form->field($model, 'price')->textInput() ?>

    <?= $form->field($model, 'price_per')->dropDownList(ProductCard::getTypesPricePer()) ?>

    <?= $form->field($model, 'database_category_id')->dropDownList(DatabaseCategory::getCategories(true)) ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/product-card/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProductCard */

$this->title = 'Добавить продукт';
$this->params['breadcrumbs'][] = ['label' => 'Продукты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="product-card-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/product-card/index.php
<?php

use app\models\ProductCard;
use richardfan\sortable\SortableGridView;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ProductCardSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Продукты';
$this->params['breadcrumbs'][] = $this->title;

$css = <<<CSS

.ui-sortable-handle:hover {
    cursor: pointer;
}

CSS;
$this->registerCss($css);

?>
<div class="product-card-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить продукт', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <p>
        <b>Записи показаны в порядке очередности отображения. Для смены очередности перетаскивайте записи.</b>
    </p>

    <?= SortableGridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'sortUrl' => Url::to(['sortItem']),
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'title',
            'is_visible:boolean',
            'is_available:boolean',
            [
                'attribute' => 'link',
                'filter'    => false,
                'format'    => 'raw',
                'value'     => function($model) {
                    /** @var ProductCard $model */
                    $url = \Yii::$app->request->baseUrl.$model->link;
                    return Html::img($url, ['alt'=>'myImage', 'width' => '25%']);
                }
            ],
            'price',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

modules/admin/views/product-card/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ProductCard */

$this->title = 'Редактирование продукта: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Продукты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="product-card-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/product-card/view.php
<?php

use app\models\ProductCard;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ProductCard */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Product Cards', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="product-card-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Уверены, что хотите удалить этот продукт?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Вернуться', ['index'], ['class' => 'btn btn-info']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'short_description:html',
            'full_description:html',
            [
                'attribute' => 'info',
                'value' => function($model) {
                    $info = [];
                    foreach ((array)json_decode($model->info) as $item) {
                        $info[] = implode(', ', (array)$item);
                    }

                    return implode(', ', $info);
                }
            ],
            'is_visible:boolean',
            'is_available:boolean',
            'is_pre_order:boolean',
            'date_available',
            'date_pre_order',
            [
                'attribute' => 'link',
                'format'    => 'raw',
                'value'     => function($model) {
                    /** @var ProductCard $model */
                    $url = \Yii::$app->request->baseUrl.$model->link;
                    return Html::img($url, ['alt'=>'myImage', 'width' => '75%']);
                }
            ],
            'price',
            [
                'attribute' => 'price_per',
                'value'     => function($model) {
                    /** @var ProductCard $model */
                    return ProductCard::getTypePricePer($model->price_per);
                }
            ],
            [
                'attribute' => 'database_category_id',
                'format'    => 'raw',
                'value'     => function($model) {
                    /** @var ProductCard $model */
                    return Html::a($model->category->title, Url::toRoute(['database-category/view', 'id' => $model->database_category_id]), ['target' => '_blank']);
                }
            ],
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>