modules/admin/controllers/AdvertisementController.php
<?php

namespace app\modules\admin\controllers;

use app\models\AdvertisementClient;
use app\services\ViberBot\ViberBot;
use Yii;
use app\models\Advertisement;
use app\models\search\AdvertisementSearch;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * AdvertisementController implements the CRUD actions for Advertisement model.
 */
class AdvertisementController extends BaseController
{
    /**
     * Lists all Advertisement models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AdvertisementSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Advertisement model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Advertisement model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Advertisement();

        if ($model->load(Yii::$app->request->post())) {

            $model->save();
            $image = UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->picture = $this->saveImage($model, $image);
            }

            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Advertisement model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $image =  UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->picture = $this->saveImage($model, $image);
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Advertisement model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        /** @var Advertisement $model */
        $model = $this->findModel($id);
        if(is_file(Yii::getAlias('@webroot').$model->picture)) {
            unlink(Yii::getAlias('@webroot').$model->picture);
        }

        AdvertisementClient::deleteAll(['advertisement_id' => $model->id]);

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Отправка рекламного сообщения
     *
     * @param $id
     * @return \yii\web\Response
     * @throws BadRequestHttpException
     */
    public function actionSend($id)
    {
        /** @var Advertisement $model */
        $model = $this->findModel($id);

        if($model->is_draft) {
            throw new BadRequestHttpException('Ошибка. Объявление в статусе черновика');
        }
        if($model->is_send) {
            throw new BadRequestHttpException('Ошибка. Объявление уже отправлено ранее');
        }

        // Отправка рекламы всем подписчикам бота
        $viberBot = new ViberBot();
        if($viberBot->sendMessage($model)) {
            $model->is_send = 1;
            $model->send_at = date('Y-m-d H:i:s');
            if($model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->redirect(['index']);
    }

    /**
     * Finds the Advertisement model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Advertisement the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Advertisement::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Сохранение изображения
     * @param $model Advertisement
     * @param $image UploadedFile
     * @return string
     */
    private function saveImage($model, $image)
    {
        $path = '/images/advertisement/'.$model->id.'_'.\Yii::$app->security->generateRandomString(8).'.'.$image->extension;

        if(!is_dir(\Yii::getAlias('@webroot').'/images/advertisement')) {
            mkdir(\Yii::getAlias('@webroot').'/images/advertisement');
        }
        $image->saveAs(\Yii::getAlias('@webroot').$path);
        return $path;
    }
}

modules/admin/controllers/ClientController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Client;
use app\models\search\ClientSearch;
use yii\web\NotFoundHttpException;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends BaseController
{

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/OrderController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Client;
use app\models\OrderDetail;
use app\models\ProductCard;
use app\services\Order\AddOrderDetail;
use app\services\Order\UpdateOrderDetail;
use Yii;
use app\models\Order;
use app\models\search\OrderSearch;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends BaseController
{
    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws ServerErrorHttpException
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post())) {

            $model->products = Yii::$app->request->post('Order')['products'];
            if($model->products == '') {
                $model->addError('products', 'Надо бы заполнить');
                return $this->render('create', [
                    'model'    => $model,
                    'clients'  => Client::getClientList(),
                    'products' => ProductCard::getProductList()
                ]);
            }
            $model->total_price = 0;
            if(!$model->save()) {
                throw new ServerErrorHttpException('Ошибка сохранения заказа');
            }

            $orderDetailService = new AddOrderDetail();
            $orderDetailService->addOrderDetail($model);

            $model->total_price = $orderDetailService->totalPrice;
            if(!$model->save()) {
                throw new ServerErrorHttpException('Ошибка сохранения заказа');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model'    => $model,
            'clients'  => Client::getClientList(),
            'products' => ProductCard::getProductList()
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param $id
     * @return string|\yii\web\Response
     * @throws ServerErrorHttpException
     */
    public function actionUpdate($id)
    {
        /** @var Order $model */
        $model = $this->findModel($id);
        $model->getProductDetails();

        if ($model->load(Yii::$app->request->post())) {

            $model->products = Yii::$app->request->post('Order')['products'];
            if($model->products == '') {
                $model->addError('products', 'Надо бы заполнить');
                return $this->render('create', [
                    'model'    => $model,
                    'clients'  => Client::getClientList(),
                    'products' => ProductCard::getProductList()
                ]);
            }

            $orderDetailService = new UpdateOrderDetail();
            $orderDetailService->updateOrderDetail($model);

            $model->total_price = $model->updateTotalPrice();

            if(!$model->save()) {
                throw new ServerErrorHttpException('Ошибка сохранения заказа');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model'    => $model,
            'clients'  => Client::getClientList(),
            'products' => ProductCard::getProductList()
        ]);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        OrderDetail::deleteAll(['order_id' => $id]);
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/ReportController.php
<?php

namespace app\modules\admin\controllers;

use app\models\forms\ReportClientFilterForm;
use app\models\forms\ReportFilterForm;
use app\models\search\OrderDetailSearch;

/**
 * Class ReportController
 * @package app\modules\admin\controllers
 */
class ReportController extends BaseController
{
    /**
     * Отчет по продуктам
     *
     * @return string
     */
    public function actionProduct()
    {
        $reportFilterForm = new ReportFilterForm();

        $searchModel = new OrderDetailSearch();

        if(\Yii::$app->request->get()) {
            $reportFilterForm->load(\Yii::$app->request->get());
        }
        $dataProvider = $searchModel->searchForReport(\Yii::$app->request->queryParams, $reportFilterForm->dateStart, $reportFilterForm->dateEnd);

        return $this->render('product', [
            'reportFilterForm' => $reportFilterForm,
            'searchModel'      => $searchModel,
            'dataProvider'     => $dataProvider,
        ]);
    }

    /**
     * Отчет по клиенту
     *
     * @return string
     */
    public function actionClient()
    {
        $reportFilterForm = new ReportClientFilterForm();

        $searchModel = new OrderDetailSearch();

        if(\Yii::$app->request->get()) {
            $reportFilterForm->load(\Yii::$app->request->get());

        }
        $dataProvider = $searchModel->searchForClientReport(\Yii::$app->request->queryParams, $reportFilterForm->client, $reportFilterForm->dateStart, $reportFilterForm->dateEnd);



        return $this->render('client', [
            'reportFilterForm' => $reportFilterForm,
            'searchModel'      => $searchModel,
            'dataProvider'     => $dataProvider,
            'issetClientId'    => isset($_GET['ReportClientFilterForm']['client'])
        ]);
    }
}

modules/admin/views/client/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */
/* @var $model app\models\Client */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'first_name')->textInput(['maxlength' => true])->label('Имя*') ?>

    <?= $form->field($model, 'middle_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->widget(MaskedInput::class, [
        'mask' => '+7 (999) 999-99-99',
        'options' => [
            'class' => 'form-control placeholder-style',
            'placeholder' => ('+7 (999) 999-99-99')
        ],
        'clientOptions' => [
            'clearIncomplete' => true
        ]
    ])->label('Телефон*') ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'has_viber')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Вернуться', ['index'], ['class' => 'btn btn-info']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/client/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = 'Добавление клиента';
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/client/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\ClientSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Клиенты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить клиента', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'first_name',
            'last_name',
            'phone',
            'email:email',
            'has_viber:boolean',
            'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

modules/admin/views/client/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = 'Редактирование клиента: ' . $model->getFullName();
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="client-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/admin/views/client/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Client */

$this->title = $model->getFullName();
$this->params['breadcrumbs'][] = ['label' => 'Clients', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="client-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Уверены, что хотите удалить этого клиента?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Вернуться', ['index'], ['class' => 'btn btn-info']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'first_name',
            'middle_name',
            'last_name',
            'phone',
            'email:email',
            'has_viber:boolean',
            'viber_id',
            'viber_name',
            'created_at',
            'updated_at',
            [
                'attribute' => 'sended_advertising',
                'label' => 'Отправленная реклама',
                'format' => 'raw',
                'value' => function($model) {
                    /** @var \app\models\AdvertisementClient[] $advertisingsClient */
                    $advertisingsClient = $model->advertisementClients;

                    if(!empty($advertisingsClient)) {
                        $string = '';

                        foreach ($advertisingsClient as $item) {

                            $string .=  Html::a($item->advertisement->name, Url::toRoute(['advertisement/view', 'id' => $item->advertisement_id]));
                            $string .= "<br>";
                        }
                        return $string;
                    }

                    return null;
                }
            ],
            [
                'attribute' => 'orders',
                'label' => 'Заказы',
                'format' => 'raw',
                'value' => function($model) {
                    $orders = $model->orders;

                    if(!empty($orders)) {
                        $string = '';

                        foreach ($orders as $item) {

                            $string .=  Html::a($item->id, Url::toRoute(['order/view', 'id' => $item->id]));
                            $string .= ' - '.$item->season.'г., на сумму '.$item->total_price.'₽';
                            $string .= "<br>";
                        }
                        $string .= "<br>";
                        $string .= Html::a('Подробный отчёт...', Url::toRoute(['report/client', 'ReportClientFilterForm[client]' => $model->id]));
                        return $string;
                    }

                    return null;
                }
            ]
        ],
    ]) ?>

</div>