modules/admin/controllers/ClientController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Client;
use app\models\search\ClientSearch;
use yii\web\NotFoundHttpException;

/**
 * ClientController implements the CRUD actions for Client model.
 */
class ClientController extends BaseController
{

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Client();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Client model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Client the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Client::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/OrderController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Client;
use app\models\OrderDetail;
use app\models\ProductCard;
use app\services\Order\AddOrderDetail;
use app\services\Order\UpdateOrderDetail;
use Yii;
use app\models\Order;
use app\models\search\OrderSearch;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends BaseController
{
    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws ServerErrorHttpException
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post())) {

            $model->products = Yii::$app->request->post('Order')['products'];
            if($model->products == '') {
                $model->addError('products', 'Надо бы заполнить');
                return $this->render('create', [
                    'model'    => $model,
                    'clients'  => Client::getClientList(),
                    'products' => ProductCard::getProductList()
                ]);
            }
            $model->total_price = 0;
            if(!$model->save()) {
                throw new ServerErrorHttpException('Ошибка сохранения заказа');
            }

            $orderDetailService = new AddOrderDetail();
            $orderDetailService->addOrderDetail($model);

            $model->total_price = $orderDetailService->totalPrice;
            if(!$model->save()) {
                throw new ServerErrorHttpException('Ошибка сохранения заказа');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model'    => $model,
            'clients'  => Client::getClientList(),
            'products' => ProductCard::getProductList()
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     *
     * @param $id
     * @return string|\yii\web\Response
     * @throws ServerErrorHttpException
     */
    public function actionUpdate($id)
    {
        /** @var Order $model */
        $model = $this->findModel($id);
        $model->getProductDetails();

        if ($model->load(Yii::$app->request->post())) {

            $model->products = Yii::$app->request->post('Order')['products'];
            if($model->products == '') {
                $model->addError('products', 'Надо бы заполнить');
                return $this->render('create', [
                    'model'    => $model,
                    'clients'  => Client::getClientList(),
                    'products' => ProductCard::getProductList()
                ]);
            }

            $orderDetailService = new UpdateOrderDetail();
            $orderDetailService->updateOrderDetail($model);

            $model->total_price = $model->updateTotalPrice();

            if(!$model->save()) {
                throw new ServerErrorHttpException('Ошибка сохранения заказа');
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model'    => $model,
            'clients'  => Client::getClientList(),
            'products' => ProductCard::getProductList()
        ]);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        OrderDetail::deleteAll(['order_id' => $id]);
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/controllers/ProductCardController.php
<?php

namespace app\modules\admin\controllers;

use richardfan\sortable\SortableAction;
use Yii;
use app\models\ProductCard;
use app\models\search\ProductCardSearch;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;

/**
 * ProductCardController implements the CRUD actions for ProductCard model.
 */
class ProductCardController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function actions(){
        return [
            'sortItem' => [
                'class' => SortableAction::class,
                'activeRecordClassName' => ProductCard::class,
                'orderColumn' => 'priority',
            ]
        ];
    }

    /**
     * Lists all ProductCard models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductCardSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ProductCard model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ProductCard model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ProductCard();

        if ($model->load(Yii::$app->request->post())) {
            if($model->info != '') {
                $model->info = json_encode($model->info, JSON_UNESCAPED_UNICODE);
            } else {
                $model->info = null;
            }
            $model->priority = $this->getNumberLastRecord();
            if($model->database_category_id == 0) {
                $model->database_category_id = null;
            }
            $model->save();
            $image = UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->link = $this->saveImage($model, $image, 'product');
            }

            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ProductCard model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            if($model->info != '') {
                $model->info = json_encode($model->info, JSON_UNESCAPED_UNICODE);
            } else {
                $model->info = null;
            }
            if($model->database_category_id == 0) {
                $model->database_category_id = null;
            }

            $image =  UploadedFile::getInstance($model, 'image');
            if(!is_null($image)) {
                $model->link = $this->saveImage($model, $image, 'product');
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }

        $model->info = json_decode($model->info);

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ProductCard model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        /** @var ProductCard $model */
        $model = $this->findModel($id);
        if(is_file(Yii::getAlias('@webroot').$model->link)) {
            unlink(Yii::getAlias('@webroot').$model->link);
        }

        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ProductCard model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ProductCard the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ProductCard::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    /**
     * Сохранение изображения
     * @param $model ProductCard
     * @param $image UploadedFile
     * @param $type string
     * @return string
     */
    private function saveImage($model, $image, $type)
    {
        $path = '/images/product/'.$model->id.'_'.$type.'.'.$image->extension;

        if(!is_dir(\Yii::getAlias('@webroot').'/images/product')) {
            mkdir(\Yii::getAlias('@webroot').'/images/product');
        }
        $image->saveAs(\Yii::getAlias('@webroot').$path);
        return $path;
    }

    /**
     * Получение номера приоритетности для новой записи
     * @return int|string
     */
    private function getNumberLastRecord()
    {
        return ProductCard::find()->count() + 1;
    }
}

modules/admin/views/order/_form.php
<?php

use app\models\Order;
use kartik\datetime\DateTimePicker;
use kartik\select2\Select2;
use unclead\multipleinput\MultipleInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $form yii\widgets\ActiveForm */
/* @var $clients array */
/* @var $products array */
?>

<div class="order-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'season')->dropDownList(Order::getAvailableSeasons()) ?>

    <?= $form->field($model, 'client_id')->widget(Select2::class, [
        'data' => $clients,
        'language' => 'ru',
        'options' => ['placeholder' => 'Выберите клиента ...'],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]) ?>

    <?= $form->field($model, 'is_delivery')->checkbox() ?>

    <?= $form->field($model, 'delivery_address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'day_of_purchase')->widget(DateTimePicker::class, [
        'language' => 'ru',
        'options' => ['placeholder' => 'Выберите дату и время покупки ...'],
        'convertFormat' => true,
        'pluginOptions' => [
            'format' => 'yyyy-M-d H:i:s',
            'todayHighlight' => true
        ]
    ]) ?>

    <?= $form->field($model, 'is_preorder')->checkbox() ?>

    <?= $form->field($model, 'products')->widget(MultipleInput::class, [
        'min' => 0,
        'max' => 15,
        'columns' => [
            [
                'name'  => 'product',
                'type'  => Select2::class,
                'title' => 'Продукт',
                'options' => ['data' => $products],
                'value' => function($data) {
                    return $data['product'];
                }
            ],
            [
                'name' => 'count',
                'type' => 'textInput',
                'title' => 'Количество',
                'value' => function($data) {
                    return $data['count'];
                }
            ]
        ]
    ])->label('Продукты в заказе') ?>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/order/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $clients array */
/* @var $products array */

$this->title = 'Добавить заказ';
$this->params['breadcrumbs'][] = ['label' => 'Заказ', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model'    => $model,
        'clients'  => $clients,
        'products' => $products
    ]) ?>

</div>

modules/admin/views/order/index.php
<?php

use app\models\Client;
use app\models\Order;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Заказы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Добавить заказ', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'season',
                'filter' => Order::getAvailableSeasons(),
                'value' => function($model) {
                    return $model->season;
                }
            ],
            [
                'attribute' => 'client_id',
                'filter' => \kartik\select2\Select2::widget([
                    'name' => 'OrderSearch[client_id]',
                    'data' => Client::getClientList(),
                    'value' => $searchModel->client_id,
                    'options' => [
                        'class' => 'form-control',
                        'placeholder' => 'Выберите клиента'
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                        'selectOnClose' => true,
                    ]
                ]),
                'format' => 'raw',
                'value' => function($model) {
                    return Html::a($model->client->getFullName(), Url::toRoute(['client/view', 'id' => $model->client_id]));
                }
            ],
            [
                'attribute' => 'products',
                'label' => 'Детали заказа',
                'format' => 'raw',
                'value' => function($model) {

                    /** @var \app\models\OrderDetail[]|null $details */
                    $details = $model->details;
                    if(is_null($details)) {
                        return null;
                    }

                    $string = '';
                    foreach ($details as $detail) {
                        $string .= Html::a($detail->product->title, Url::toRoute(['product-card/view', ['id' => $detail->product_card_id]]));
                        $string .= '('.\app\models\ProductCard::getTypePricePer($detail->units).')';
                        $string .= " - <b>".$detail->count."</b>";
                        $string .= "<br>";
                    }

                    return $string;
                }
            ],
            'total_price',
            'day_of_purchase',
            'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

modules/admin/views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $clients array */
/* @var $products array */

$this->title = 'Редактирование заказа№' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model'    => $model,
        'clients'  => $clients,
        'products' => $products
    ]) ?>

</div>

modules/admin/views/order/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Заказ №'.$model->id;
$this->params['breadcrumbs'][] = ['label' => 'Заказы', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="order-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Уверены что хотите удалить этот заказ?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Вернуться', ['index'], ['class' => 'btn btn-info']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'season',
            [
                'attribute' => 'client_id',
                'format' => 'raw',
                'value' => function($model) {
                    return Html::a($model->client->getFullName(), Url::toRoute(['client/view', 'id' => $model->client_id]));
                }
            ],
            'total_price',
            [
                'attribute' => 'products',
                'label' => 'Детали заказа',
                'format' => 'raw',
                'value' => function($model) {

                    /** @var \app\models\OrderDetail[]|null $details */
                    $details = $model->details;
                    if(is_null($details)) {
                        return null;
                    }

                    $string = '';
                    foreach ($details as $detail) {
                        $string .= Html::a($detail->product->title, Url::toRoute(['product-card/view', 'id' => $detail->product_card_id]));
                        $string .= '('.\app\models\ProductCard::getTypePricePer($detail->units).')';
                        $string .= " - <b>".$detail->count."</b>";
                        $string .= "<br>";
                    }

                    return $string;
                }
            ],
            'is_delivery:boolean',
            'delivery_address',
            'day_of_purchase',
            'is_preorder:boolean',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>