modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use app\models\AdminUser;
use app\models\forms\LoginForm;
use app\models\forms\RequestChangePasswordForm;
use app\models\forms\ResetPasswordForm;
use app\modules\admin\services\ChangePasswordService;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends BaseController
{
    public $layout = 'login';

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $this->layout = 'admin';

        return $this->redirect(Url::toRoute('main-page-info/index'));
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect('/admin/default/index');
        }

        $model = new LoginForm();
        if ($model->load(\Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/admin/default/index');
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        \Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Страница запроса смены пароля администратора
     * @return string
     */
    public function actionRequestChangePassword()
    {
        if(\Yii::$app->request->post()) {
            $changeService = new ChangePasswordService();

            if($isSend = $changeService->sendMessageForUser($_POST['RequestChangePasswordForm']['login'])) {
                $email = $_POST['RequestChangePasswordForm']['login'];
            }
        }

        return $this->render('request-change-password', [
            'model'  => new RequestChangePasswordForm(),
            'isSend' => isset($isSend) ? $isSend : null,
            'email'  => isset($email) ? $email : null
        ]);
    }

    /**
     * Создание нового пароля для администратора
     * @return string|Response
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     */
    public function actionResetPassword()
    {
        $token = \Yii::$app->request->get('token');

        if(is_null($token)) {
            throw new BadRequestHttpException('Отсутствует обязательный параметр token');
        }

        $existToken = AdminUser::findOne(['reset_token' => $token]);

        if(is_null($existToken)) {
            throw new NotFoundHttpException('Отсутствует пользователь с переданным токеном');
        }

        if(\Yii::$app->request->post()) {
            $changeService = new ChangePasswordService();
            if($changeService->changePassword($_POST['ResetPasswordForm']['password'])) {
                return $this->redirect('index');
            } else {
                $error = true;
            }
        }

        return $this->render('reset-password', [
            'model' => new ResetPasswordForm(),
            'error' => isset($error) ? $error : null
        ]);
    }
}

modules/admin/views/default/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

modules/admin/views/default/index.php
<?= \yii\helpers\Html::a('Обратные звонки', \yii\helpers\Url::toRoute(['/admin/callback/index'])) ?>
<br>
<?= \yii\helpers\Html::a('Вопросы', \yii\helpers\Url::toRoute(['/admin/question/index'])) ?>
<br>
<?= \yii\helpers\Html::a('Заявки', \yii\helpers\Url::toRoute(['/admin/request/index'])) ?>
<br>
<?= \yii\helpers\Html::a('Отзывы', \yii\helpers\Url::toRoute(['/admin/review/index'])) ?>
<br>

modules/admin/views/default/login.php
<?php

/**
 * @var $this yii\web\View
 * @var $form yii\bootstrap\ActiveForm
 * @var $model app\models\forms\LoginForm
 */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Авторизация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для входа:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username')
        ->textInput(['autofocus' => true])
        ->label('Логин') ?>

    <?= $form->field($model, 'password')
        ->passwordInput()
        ->label('Пароль') ?>

    <?= $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->label('Запомнить меня') ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <br>
    <div class="col-md-offset-1 col-md-3">
        <?= Html::a('Забыли пароль?', Url::toRoute(['default/request-change-password'])) ?>
    </div>
</div>

modules/admin/views/default/request-change-password.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\forms\RequestChangePasswordForm */
/* @var $isSend bool */
/* @var $email string */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="col-md-3"></div>
    <div class="row">
        <div class="col-lg-5">

            <?php if($isSend) { ?>
                <div class="alert alert-success">
                    На указанный email <strong>"<?= $email ?>"</strong> отправлено письмо с инструкциями. Проверьте почтовый ящик.
                </div>
            <?php } else { ?>
                <div class="alert alert-info">
                    <b>Введите свой e-mail и мы отправим Вам письмо с инструкциями</b>
                </div>
            <?php } ?>

            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <?= $form->field($model, 'login')->textInput(['autofocus' => true]) ?>

            <div class="form-group">
                <?= Html::submitButton('Отправить письмо', ['class' => 'btn btn-success', 'name' => 'login-button']) ?>
                <?= Html::a('Вернуться', Url::toRoute('default/index'), ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

modules/admin/views/default/reset-password.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\forms\ResetPasswordForm */
/* @var $isSend bool */
/* @var $email string */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

?>

<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <div class="col-md-3"></div>
    <div class="row">
        <div class="col-lg-5">

            <?php if(isset($error)) { ?>
                <div class="alert alert-danger">
                    При смене пароля произошла ошибка. Новый пароль не сохранен
                </div>
            <?php } else { ?>
                <div class="alert alert-info">
                    <b>Для смены текущего пароля введите новый пароль дважды.</b>
                </div>
            <?php } ?>

            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <?= $form->field($model, 'password')->passwordInput([
                'autofocus' => true,
                'placeholder' => 'Введите новый пароль'
            ]) ?>

            <?= $form->field($model, 'repeatPassword')->passwordInput([
                'placeholder' => 'Введите пароль еще раз'
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton('Сменить пароль', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>